
acme_partial_product_latest:
    path: /latest
    defaults:
        _controller: acme.controller.frontend.homepage:indexAction
        # _acme:
        #     limit: $limit
        #     template: $template
