# services:
#    acme_user.example:
#        class: Acme\Bundle\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

parameters:
    acme.controller.customer.class: Acme\Bundle\UserBundle\Controller\CustomerController

services:
    acme.controller.customer:
        class:        %acme.controller.customer.class%
        calls:
          - [setContainer, ["@service_container"]]